### ISSUE TITLE
setting up infrastructure for aws using terraform

### ISSUE THREAD

**Issue by y1450** [y1450/de-zoomcamp#2]
#Tasks

- [x] Create a vpc 
- [x] Create a gateway
- [x] create a private subnet
- [x] create a public subnet
- [x] create a ec2 instance
- [ ] create a s3 storage bucket
- [ ] create a redshift cluster

Docs:
https://github.com/jralduaveuthey/data-eng-zc-gcp-aws/blob/33bfb6606d9967908b9d1bc3eaeb3ff7eff9b878/week_2_workflow_orchestration/prefect-zoomcamp/flows/02_aws/etl_s3_to_redshift.py#L96

**Comment by y1450** [comment]
https://medium.com/strategio/using-terraform-to-create-aws-vpc-ec2-and-rds-instances-c7f3aa416133

**Comment by y1450** [comment]
https://docs.aws.amazon.com/vpc/latest/userguide/what-is-amazon-vpc.html

**Comment by y1450** [comment]
https://stackoverflow.com/questions/67963719/should-terraform-lock-hcl-be-included-in-the-gitignore-file

**Comment by y1450** [comment]
```mermaid
---
title: AWS infrastructure
---
flowchart LR
    VPC\ntag:prefect_vpc
```

**Comment by y1450** [comment]
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/subnet

**Comment by y1450** [comment]
https://www.youtube.com/watch?v=g2JOHLHh4rI

**Comment by y1450** [comment]
![image](https://user-images.githubusercontent.com/107429941/218236556-a94e48ba-fcc3-4903-8aa1-49fc4f47b4d6.png)

**Comment by y1450** [comment]
![image](https://user-images.githubusercontent.com/107429941/218236658-1ad56dbf-bb8c-4dd5-a500-2be27313bdc0.png)

**Comment by y1450** [comment]
![image](https://user-images.githubusercontent.com/107429941/218236941-db11c884-3b32-4dfa-a19a-b6342cb6496d.png)

**Comment by y1450** [comment]
security group is state ful and return traffic is allowed automatically.
network acl is stateless and requires both inbound and outboud rule.

**Comment by y1450** [comment]
![image](https://user-images.githubusercontent.com/107429941/218237183-b3a6b43c-ded9-4c82-bd6b-7d09b5255955.png)

**Comment by y1450** [comment]
![aws_infrastructure](https://user-images.githubusercontent.com/107429941/218246219-e6c043b1-3b83-4e6f-bbae-c2211300d17a.svg)

**Comment by y1450** [comment]
S3 bucket are not managed in vpc and are offered a service solution. To access s3 vpc needs to have access internet which can be done using vpc end points.
https://aws.amazon.com/blogs/storage/managing-amazon-s3-access-with-vpc-endpoints-and-s3-access-points/
